name: cresce_flutter_app
description: Cresce flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^0.13.1
  equatable: ^2.0.0
  provider: ^5.0.0
  loading: ^1.0.2
  font_awesome_flutter: ^9.0.0
  intl: ^0.17.0
  syncfusion_flutter_calendar: ^19.1.57
  syncfusion_localizations: ^19.1.57

dependency_overrides:
  loading:
    git:
      url: git://github.com/leonzone/loading.git
      path: loading
      ref: 8f5a63f

  timezone: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.0.5


flutter:
  generate: true
  uses-material-design: true
  assets:
    - packages/timezone/data/2020a.tzf