name: cresce_flutter_app
description: Cresce flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ui_bits: ^0.0.5
  font_awesome_flutter: ^8.10.0
  http: ^0.12.2
  equatable: ^1.2.5
  cupertino_icons: ^0.1.3
  provider: ^4.3.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.0

flutter:

  uses-material-design: true
